import re

from dataclasses import dataclass
from typing import List

@dataclass
class Country:
    name: str
    alpha2: str
    alpha3: str
    numberic: int

COUNTRIES = [
    Country("Afghanistan", "AF", "AFG", 4),
    Country("Albania", "AL", "ALB", 8),
    Country("Algeria", "DZ", "DZA", 12),
    Country("American Samoa", "AS", "ASM", 16),
    Country("Andorra", "AD", "AND", 20),
    Country("Angola", "AO", "AGO", 24),
    Country("Anguilla", "AI", "AIA", 660),
    Country("Antarctica", "AQ", "ATA", 10),
    Country("Antigua and Barbuda", "AG", "ATG", 28),
    Country("Argentina", "AR", "ARG", 32),
    Country("Armenia", "AM", "ARM", 51),
    Country("Aruba", "AW", "ABW", 533),
    Country("Australia", "AU", "AUS", 36),
    Country("Austria", "AT", "AUT", 40),
    Country("Azerbaijan", "AZ", "AZE", 31),
    Country("Bahamas (the)", "BS", "BHS", 44),
    Country("Bahrain", "BH", "BHR", 48),
    Country("Bangladesh", "BD", "BGD", 50),
    Country("Barbados", "BB", "BRB", 52),
    Country("Belarus", "BY", "BLR", 112),
    Country("Belgium", "BE", "BEL", 56),
    Country("Belize", "BZ", "BLZ", 84),
    Country("Benin", "BJ", "BEN", 204),
    Country("Bermuda", "BM", "BMU", 60),
    Country("Bhutan", "BT", "BTN", 64),
    Country("Bolivia (Plurinational State of)", "BO", "BOL", 68),
    Country("Bonaire, Sint Eustatius and Saba", "BQ", "BES", 535),
    Country("Bosnia and Herzegovina", "BA", "BIH", 70),
    Country("Botswana", "BW", "BWA", 72),
    Country("Bouvet Island", "BV", "BVT", 74),
    Country("Brazil", "BR", "BRA", 76),
    Country("British Indian Ocean Territory (the)", "IO", "IOT", 86),
    Country("Brunei Darussalam", "BN", "BRN", 96),
    Country("Bulgaria", "BG", "BGR", 100),
    Country("Burkina Faso", "BF", "BFA", 854),
    Country("Burundi", "BI", "BDI", 108),
    Country("Cabo Verde", "CV", "CPV", 132),
    Country("Cambodia", "KH", "KHM", 116),
    Country("Cameroon", "CM", "CMR", 120),
    Country("Canada", "CA", "CAN", 124),
    Country("Cayman Islands (the)", "KY", "CYM", 136),
    Country("Central African Republic (the)", "CF", "CAF", 140),
    Country("Chad", "TD", "TCD", 148),
    Country("Chile", "CL", "CHL", 152),
    Country("China", "CN", "CHN", 156),
    Country("Christmas Island", "CX", "CXR", 162),
    Country("Cocos (Keeling) Islands (the)", "CC", "CCK", 166),
    Country("Colombia", "CO", "COL", 170),
    Country("Comoros (the)", "KM", "COM", 174),
    Country("Congo (the Democratic Republic of the)", "CD", "COD", 180),
    Country("Congo (the)", "CG", "COG", 178),
    Country("Cook Islands (the)", "CK", "COK", 184),
    Country("Costa Rica", "CR", "CRI", 188),
    Country("Croatia", "HR", "HRV", 191),
    Country("Cuba", "CU", "CUB", 192),
    Country("Curaçao", "CW", "CUW", 531),
    Country("Cyprus", "CY", "CYP", 196),
    Country("Czechia", "CZ", "CZE", 203),
    Country("Côte d'Ivoire", "CI", "CIV", 384),
    Country("Denmark", "DK", "DNK", 208),
    Country("Djibouti", "DJ", "DJI", 262),
    Country("Dominica", "DM", "DMA", 212),
    Country("Dominican Republic (the)", "DO", "DOM", 214),
    Country("Ecuador", "EC", "ECU", 218),
    Country("Egypt", "EG", "EGY", 818),
    Country("El Salvador", "SV", "SLV", 222),
    Country("Equatorial Guinea", "GQ", "GNQ", 226),
    Country("Eritrea", "ER", "ERI", 232),
    Country("Estonia", "EE", "EST", 233),
    Country("Eswatini", "SZ", "SWZ", 748),
    Country("Ethiopia", "ET", "ETH", 231),
    Country("Falkland Islands (the) [Malvinas]", "FK", "FLK", 238),
    Country("Faroe Islands (the)", "FO", "FRO", 234),
    Country("Fiji", "FJ", "FJI", 242),
    Country("Finland", "FI", "FIN", 246),
    Country("France", "FR", "FRA", 250),
    Country("French Guiana", "GF", "GUF", 254),
    Country("French Polynesia", "PF", "PYF", 258),
    Country("French Southern Territories (the)", "TF", "ATF", 260),
    Country("Gabon", "GA", "GAB", 266),
    Country("Gambia (the)", "GM", "GMB", 270),
    Country("Georgia", "GE", "GEO", 268),
    Country("Germany", "DE", "DEU", 276),
    Country("Ghana", "GH", "GHA", 288),
    Country("Gibraltar", "GI", "GIB", 292),
    Country("Greece", "GR", "GRC", 300),
    Country("Greenland", "GL", "GRL", 304),
    Country("Grenada", "GD", "GRD", 308),
    Country("Guadeloupe", "GP", "GLP", 312),
    Country("Guam", "GU", "GUM", 316),
    Country("Guatemala", "GT", "GTM", 320),
    Country("Guernsey", "GG", "GGY", 831),
    Country("Guinea", "GN", "GIN", 324),
    Country("Guinea-Bissau", "GW", "GNB", 624),
    Country("Guyana", "GY", "GUY", 328),
    Country("Haiti", "HT", "HTI", 332),
    Country("Heard Island and McDonald Islands", "HM", "HMD", 334),
    Country("Holy See (the)", "VA", "VAT", 336),
    Country("Honduras", "HN", "HND", 340),
    Country("Hong Kong", "HK", "HKG", 344),
    Country("Hungary", "HU", "HUN", 348),
    Country("Iceland", "IS", "ISL", 352),
    Country("India", "IN", "IND", 356),
    Country("Indonesia", "ID", "IDN", 360),
    Country("Iran (Islamic Republic of)", "IR", "IRN", 364),
    Country("Iraq", "IQ", "IRQ", 368),
    Country("Ireland", "IE", "IRL", 372),
    Country("Isle of Man", "IM", "IMN", 833),
    Country("Israel", "IL", "ISR", 376),
    Country("Italy", "IT", "ITA", 380),
    Country("Jamaica", "JM", "JAM", 388),
    Country("Japan", "JP", "JPN", 392),
    Country("Jersey", "JE", "JEY", 832),
    Country("Jordan", "JO", "JOR", 400),
    Country("Kazakhstan", "KZ", "KAZ", 398),
    Country("Kenya", "KE", "KEN", 404),
    Country("Kiribati", "KI", "KIR", 296),
    Country("Korea (the Democratic People's Republic of)", "KP", "PRK", 408),
    Country("Korea (the Republic of)", "KR", "KOR", 410),
    Country("Kuwait", "KW", "KWT", 414),
    Country("Kyrgyzstan", "KG", "KGZ", 417),
    Country("Lao People's Democratic Republic (the)", "LA", "LAO", 418),
    Country("Latvia", "LV", "LVA", 428),
    Country("Lebanon", "LB", "LBN", 422),
    Country("Lesotho", "LS", "LSO", 426),
    Country("Liberia", "LR", "LBR", 430),
    Country("Libya", "LY", "LBY", 434),
    Country("Liechtenstein", "LI", "LIE", 438),
    Country("Lithuania", "LT", "LTU", 440),
    Country("Luxembourg", "LU", "LUX", 442),
    Country("Macao", "MO", "MAC", 446),
    Country("Madagascar", "MG", "MDG", 450),
    Country("Malawi", "MW", "MWI", 454),
    Country("Malaysia", "MY", "MYS", 458),
    Country("Maldives", "MV", "MDV", 462),
    Country("Mali", "ML", "MLI", 466),
    Country("Malta", "MT", "MLT", 470),
    Country("Marshall Islands (the)", "MH", "MHL", 584),
    Country("Martinique", "MQ", "MTQ", 474),
    Country("Mauritania", "MR", "MRT", 478),
    Country("Mauritius", "MU", "MUS", 480),
    Country("Mayotte", "YT", "MYT", 175),
    Country("Mexico", "MX", "MEX", 484),
    Country("Micronesia (Federated States of)", "FM", "FSM", 583),
    Country("Moldova (the Republic of)", "MD", "MDA", 498),
    Country("Monaco", "MC", "MCO", 492),
    Country("Mongolia", "MN", "MNG", 496),
    Country("Montenegro", "ME", "MNE", 499),
    Country("Montserrat", "MS", "MSR", 500),
    Country("Morocco", "MA", "MAR", 504),
    Country("Mozambique", "MZ", "MOZ", 508),
    Country("Myanmar", "MM", "MMR", 104),
    Country("Namibia", "NA", "NAM", 516),
    Country("Nauru", "NR", "NRU", 520),
    Country("Nepal", "NP", "NPL", 524),
    Country("Netherlands (the)", "NL", "NLD", 528),
    Country("New Caledonia", "NC", "NCL", 540),
    Country("New Zealand", "NZ", "NZL", 554),
    Country("Nicaragua", "NI", "NIC", 558),
    Country("Niger (the)", "NE", "NER", 562),
    Country("Nigeria", "NG", "NGA", 566),
    Country("Niue", "NU", "NIU", 570),
    Country("Norfolk Island", "NF", "NFK", 574),
    Country("Northern Mariana Islands (the)", "MP", "MNP", 580),
    Country("Norway", "NO", "NOR", 578),
    Country("Oman", "OM", "OMN", 512),
    Country("Pakistan", "PK", "PAK", 586),
    Country("Palau", "PW", "PLW", 585),
    Country("Palestine, State of", "PS", "PSE", 275),
    Country("Panama", "PA", "PAN", 591),
    Country("Papua New Guinea", "PG", "PNG", 598),
    Country("Paraguay", "PY", "PRY", 600),
    Country("Peru", "PE", "PER", 604),
    Country("Philippines (the)", "PH", "PHL", 608),
    Country("Pitcairn", "PN", "PCN", 612),
    Country("Poland", "PL", "POL", 616),
    Country("Portugal", "PT", "PRT", 620),
    Country("Puerto Rico", "PR", "PRI", 630),
    Country("Qatar", "QA", "QAT", 634),
    Country("Republic of North Macedonia", "MK", "MKD", 807),
    Country("Romania", "RO", "ROU", 642),
    Country("Russian Federation (the)", "RU", "RUS", 643),
    Country("Rwanda", "RW", "RWA", 646),
    Country("Réunion", "RE", "REU", 638),
    Country("Saint Barthélemy", "BL", "BLM", 652),
    Country("Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", 654),
    Country("Saint Kitts and Nevis", "KN", "KNA", 659),
    Country("Saint Lucia", "LC", "LCA", 662),
    Country("Saint Martin (French part)", "MF", "MAF", 663),
    Country("Saint Pierre and Miquelon", "PM", "SPM", 666),
    Country("Saint Vincent and the Grenadines", "VC", "VCT", 670),
    Country("Samoa", "WS", "WSM", 882),
    Country("San Marino", "SM", "SMR", 674),
    Country("Sao Tome and Principe", "ST", "STP", 678),
    Country("Saudi Arabia", "SA", "SAU", 682),
    Country("Senegal", "SN", "SEN", 686),
    Country("Serbia", "RS", "SRB", 688),
    Country("Seychelles", "SC", "SYC", 690),
    Country("Sierra Leone", "SL", "SLE", 694),
    Country("Singapore", "SG", "SGP", 702),
    Country("Sint Maarten (Dutch part)", "SX", "SXM", 534),
    Country("Slovakia", "SK", "SVK", 703),
    Country("Slovenia", "SI", "SVN", 705),
    Country("Solomon Islands", "SB", "SLB", 90),
    Country("Somalia", "SO", "SOM", 706),
    Country("South Africa", "ZA", "ZAF", 710),
    Country("South Georgia and the South Sandwich Islands", "GS", "SGS", 239),
    Country("South Sudan", "SS", "SSD", 728),
    Country("Spain", "ES", "ESP", 724),
    Country("Sri Lanka", "LK", "LKA", 144),
    Country("Sudan (the)", "SD", "SDN", 729),
    Country("Suriname", "SR", "SUR", 740),
    Country("Svalbard and Jan Mayen", "SJ", "SJM", 744),
    Country("Sweden", "SE", "SWE", 752),
    Country("Switzerland", "CH", "CHE", 756),
    Country("Syrian Arab Republic", "SY", "SYR", 760),
    Country("Taiwan (Province of China)", "TW", "TWN", 158),
    Country("Tajikistan", "TJ", "TJK", 762),
    Country("Tanzania, United Republic of", "TZ", "TZA", 834),
    Country("Thailand", "TH", "THA", 764),
    Country("Timor-Leste", "TL", "TLS", 626),
    Country("Togo", "TG", "TGO", 768),
    Country("Tokelau", "TK", "TKL", 772),
    Country("Tonga", "TO", "TON", 776),
    Country("Trinidad and Tobago", "TT", "TTO", 780),
    Country("Tunisia", "TN", "TUN", 788),
    Country("Turkey", "TR", "TUR", 792),
    Country("Turkmenistan", "TM", "TKM", 795),
    Country("Turks and Caicos Islands (the)", "TC", "TCA", 796),
    Country("Tuvalu", "TV", "TUV", 798),
    Country("Uganda", "UG", "UGA", 800),
    Country("Ukraine", "UA", "UKR", 804),
    Country("United Arab Emirates (the)", "AE", "ARE", 784),
    Country("United Kingdom of Great Britain and Northern Ireland (the)", "GB", "GBR", 826),
    Country("United States Minor Outlying Islands (the)", "UM", "UMI", 581),
    Country("United States of America (the)", "US", "USA", 840),
    Country("Uruguay", "UY", "URY", 858),
    Country("Uzbekistan", "UZ", "UZB", 860),
    Country("Vanuatu", "VU", "VUT", 548),
    Country("Venezuela (Bolivarian Republic of)", "VE", "VEN", 862),
    Country("Viet Nam", "VN", "VNM", 704),
    Country("Virgin Islands (British)", "VG", "VGB", 92),
    Country("Virgin Islands (U.S.)", "VI", "VIR", 850),
    Country("Wallis and Futuna", "WF", "WLF", 876),
    Country("Western Sahara", "EH", "ESH", 732),
    Country("Yemen", "YE", "YEM", 887),
    Country("Zambia", "ZM", "ZMB", 894),
    Country("Zimbabwe", "ZW", "ZWE", 716),
    Country("Åland Islands", "AX", "ALA", 248),
]

COUNTRY_CODES = {
    country.alpha2: country for country in COUNTRIES
}

def search_country(regex: str) -> List[Country]:
    results = []
    for country in COUNTRIES:
        if re.search(regex, country.name):
            results.append(country)
    return results

def to_country_code(regex: str) -> str:
    """
    Returns the alpha2 code of the country that matches the given regex.
    If multiple countries match the regex, the search fails.
    """
    countries = search_country(regex)
    if len(countries) == 0:
        raise ValueError("No countries match the regex")
    if len(countries) > 1:
        raise ValueError("Multiple countries match")
    return countries[0].alpha2

def validate_country_code(code: str) -> bool:
    """
    Returns True if the given code is a valid alpha2 country code.
    """
    return code in COUNTRY_CODES
